version: "3.7"
services:
  api:
    build:
      context: ./
      dockerfile: api.Dockerfile
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8081
      published: "8081"
      protocol: tcp
  ui:
    environment: 
      - TARGET_HOST=10.20.14.129:8081
    build:
      context: ./
      dockerfile: ui.Dockerfile
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
networks:
  default:
    name: docker_default
