name: docker
services:
  api:
    build:
      context: /Users/20045478/Documents/my_projects/doker/DemidovLab/docker
      dockerfile: api.Dockerfile
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8081
      published: "8081"
      protocol: tcp
  ui:
    build:
      context: /Users/20045478/Documents/my_projects/doker/DemidovLab/docker
      dockerfile: ui.Dockerfile
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
networks:
  default:
    name: docker_default