services:
  api: 
    build: 
      context: ./
      dockerfile: api.Dockerfile
    ports:
      - 8081:8081
  ui:
    build: 
      context: ./
      dockerfile: ui.Dockerfile
    ports:
      - 8080:8080

