kind: Deployment
apiVersion: apps/v1
metadata:
  name: ui
  namespace: default
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ssh
          image: fparadox/demidov:ui
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: TARGET_HOST
              value: ui.default
          resources: 
            limits:
              cpu: 300m
              memory: 300Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: pull-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

