apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJmcGFyYWRveCIsInBhc3N3b3JkIjoiVmlrdDByLnBhc3MiLCJhdXRoIjoiWm5CaGNtRmtiM2c2Vm1scmREQnlMbkJoYzNNPSJ9fX0=
kind: Secret
metadata:
  name: pull-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
